version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todolist
    ports:
      - "5432:5432"
    volumes:
      - dbdata_postgre:/var/lib/postgresql/data

  go:
    container_name: go
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "postgres"

volumes:
  dbdata_postgre: